name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: dautraver/github-readme-snake@v1
        with:
          github_user_name: Serpentum
          output_file_path: output/snake.svg
          color_palette: github-dark

      - name: Generate Neon Snake
        uses: dautraver/github-readme-snake@v1
        with:
          github_user_name: Serpentum
          output_file_path: output/snake-neon.svg
          color_palette: neon

      - name: Commit and push
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add output/
          git diff --staged --quiet || git commit -m "chore: update snake animation"
          git push
